{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}-auth
type: Opaque
stringData:
  password: {{ .Values.auth.password | quote }}
{{- end }}
